language: python
python : "3.9"
sudo : required
os: linux
dist: focal
arch: amd64
services: docker
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - perfect2101@naver.com
branches:
  only:
    - main
    - develop

